# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/haicoin/.openclaw/workspace/lvgl-zero2w

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/haicoin/.openclaw/workspace/lvgl-zero2w/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haicoin/.openclaw/workspace/lvgl-zero2w/build/CMakeFiles /home/haicoin/.openclaw/workspace/lvgl-zero2w/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haicoin/.openclaw/workspace/lvgl-zero2w/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lv_drivers

# Build rule for target.
lv_drivers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lv_drivers
.PHONY : lv_drivers

# fast build rule for target.
lv_drivers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/build
.PHONY : lv_drivers/fast

#=============================================================================
# Target rules for targets named app_ui

# Build rule for target.
app_ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app_ui
.PHONY : app_ui

# fast build rule for target.
app_ui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_ui.dir/build.make CMakeFiles/app_ui.dir/build
.PHONY : app_ui/fast

#=============================================================================
# Target rules for targets named lvgl-sim

# Build rule for target.
lvgl-sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl-sim
.PHONY : lvgl-sim

# fast build rule for target.
lvgl-sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl-sim.dir/build.make CMakeFiles/lvgl-sim.dir/build
.PHONY : lvgl-sim/fast

#=============================================================================
# Target rules for targets named lvgl

# Build rule for target.
lvgl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl
.PHONY : lvgl

# fast build rule for target.
lvgl/fast:
	$(MAKE) $(MAKESILENT) -f _deps/lvgl-build/CMakeFiles/lvgl.dir/build.make _deps/lvgl-build/CMakeFiles/lvgl.dir/build
.PHONY : lvgl/fast

#=============================================================================
# Target rules for targets named lvgl_examples

# Build rule for target.
lvgl_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_examples
.PHONY : lvgl_examples

# fast build rule for target.
lvgl_examples/fast:
	$(MAKE) $(MAKESILENT) -f _deps/lvgl-build/CMakeFiles/lvgl_examples.dir/build.make _deps/lvgl-build/CMakeFiles/lvgl_examples.dir/build
.PHONY : lvgl_examples/fast

#=============================================================================
# Target rules for targets named lvgl_demos

# Build rule for target.
lvgl_demos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_demos
.PHONY : lvgl_demos

# fast build rule for target.
lvgl_demos/fast:
	$(MAKE) $(MAKESILENT) -f _deps/lvgl-build/CMakeFiles/lvgl_demos.dir/build.make _deps/lvgl-build/CMakeFiles/lvgl_demos.dir/build
.PHONY : lvgl_demos/fast

_deps/lv_drivers-src/display/fbdev.o: _deps/lv_drivers-src/display/fbdev.c.o
.PHONY : _deps/lv_drivers-src/display/fbdev.o

# target to build an object file
_deps/lv_drivers-src/display/fbdev.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/display/fbdev.c.o
.PHONY : _deps/lv_drivers-src/display/fbdev.c.o

_deps/lv_drivers-src/display/fbdev.i: _deps/lv_drivers-src/display/fbdev.c.i
.PHONY : _deps/lv_drivers-src/display/fbdev.i

# target to preprocess a source file
_deps/lv_drivers-src/display/fbdev.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/display/fbdev.c.i
.PHONY : _deps/lv_drivers-src/display/fbdev.c.i

_deps/lv_drivers-src/display/fbdev.s: _deps/lv_drivers-src/display/fbdev.c.s
.PHONY : _deps/lv_drivers-src/display/fbdev.s

# target to generate assembly for a file
_deps/lv_drivers-src/display/fbdev.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/display/fbdev.c.s
.PHONY : _deps/lv_drivers-src/display/fbdev.c.s

_deps/lv_drivers-src/indev/evdev.o: _deps/lv_drivers-src/indev/evdev.c.o
.PHONY : _deps/lv_drivers-src/indev/evdev.o

# target to build an object file
_deps/lv_drivers-src/indev/evdev.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/indev/evdev.c.o
.PHONY : _deps/lv_drivers-src/indev/evdev.c.o

_deps/lv_drivers-src/indev/evdev.i: _deps/lv_drivers-src/indev/evdev.c.i
.PHONY : _deps/lv_drivers-src/indev/evdev.i

# target to preprocess a source file
_deps/lv_drivers-src/indev/evdev.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/indev/evdev.c.i
.PHONY : _deps/lv_drivers-src/indev/evdev.c.i

_deps/lv_drivers-src/indev/evdev.s: _deps/lv_drivers-src/indev/evdev.c.s
.PHONY : _deps/lv_drivers-src/indev/evdev.s

# target to generate assembly for a file
_deps/lv_drivers-src/indev/evdev.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/indev/evdev.c.s
.PHONY : _deps/lv_drivers-src/indev/evdev.c.s

_deps/lv_drivers-src/sdl/sdl.o: _deps/lv_drivers-src/sdl/sdl.c.o
.PHONY : _deps/lv_drivers-src/sdl/sdl.o

# target to build an object file
_deps/lv_drivers-src/sdl/sdl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/sdl/sdl.c.o
.PHONY : _deps/lv_drivers-src/sdl/sdl.c.o

_deps/lv_drivers-src/sdl/sdl.i: _deps/lv_drivers-src/sdl/sdl.c.i
.PHONY : _deps/lv_drivers-src/sdl/sdl.i

# target to preprocess a source file
_deps/lv_drivers-src/sdl/sdl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/sdl/sdl.c.i
.PHONY : _deps/lv_drivers-src/sdl/sdl.c.i

_deps/lv_drivers-src/sdl/sdl.s: _deps/lv_drivers-src/sdl/sdl.c.s
.PHONY : _deps/lv_drivers-src/sdl/sdl.s

# target to generate assembly for a file
_deps/lv_drivers-src/sdl/sdl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/sdl/sdl.c.s
.PHONY : _deps/lv_drivers-src/sdl/sdl.c.s

_deps/lv_drivers-src/sdl/sdl_common.o: _deps/lv_drivers-src/sdl/sdl_common.c.o
.PHONY : _deps/lv_drivers-src/sdl/sdl_common.o

# target to build an object file
_deps/lv_drivers-src/sdl/sdl_common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/sdl/sdl_common.c.o
.PHONY : _deps/lv_drivers-src/sdl/sdl_common.c.o

_deps/lv_drivers-src/sdl/sdl_common.i: _deps/lv_drivers-src/sdl/sdl_common.c.i
.PHONY : _deps/lv_drivers-src/sdl/sdl_common.i

# target to preprocess a source file
_deps/lv_drivers-src/sdl/sdl_common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/sdl/sdl_common.c.i
.PHONY : _deps/lv_drivers-src/sdl/sdl_common.c.i

_deps/lv_drivers-src/sdl/sdl_common.s: _deps/lv_drivers-src/sdl/sdl_common.c.s
.PHONY : _deps/lv_drivers-src/sdl/sdl_common.s

# target to generate assembly for a file
_deps/lv_drivers-src/sdl/sdl_common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lv_drivers.dir/build.make CMakeFiles/lv_drivers.dir/_deps/lv_drivers-src/sdl/sdl_common.c.s
.PHONY : _deps/lv_drivers-src/sdl/sdl_common.c.s

src/fonts/lv_font_cn_14.o: src/fonts/lv_font_cn_14.c.o
.PHONY : src/fonts/lv_font_cn_14.o

# target to build an object file
src/fonts/lv_font_cn_14.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_ui.dir/build.make CMakeFiles/app_ui.dir/src/fonts/lv_font_cn_14.c.o
.PHONY : src/fonts/lv_font_cn_14.c.o

src/fonts/lv_font_cn_14.i: src/fonts/lv_font_cn_14.c.i
.PHONY : src/fonts/lv_font_cn_14.i

# target to preprocess a source file
src/fonts/lv_font_cn_14.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_ui.dir/build.make CMakeFiles/app_ui.dir/src/fonts/lv_font_cn_14.c.i
.PHONY : src/fonts/lv_font_cn_14.c.i

src/fonts/lv_font_cn_14.s: src/fonts/lv_font_cn_14.c.s
.PHONY : src/fonts/lv_font_cn_14.s

# target to generate assembly for a file
src/fonts/lv_font_cn_14.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_ui.dir/build.make CMakeFiles/app_ui.dir/src/fonts/lv_font_cn_14.c.s
.PHONY : src/fonts/lv_font_cn_14.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl-sim.dir/build.make CMakeFiles/lvgl-sim.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl-sim.dir/build.make CMakeFiles/lvgl-sim.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl-sim.dir/build.make CMakeFiles/lvgl-sim.dir/src/main.c.s
.PHONY : src/main.c.s

src/ui_demo.o: src/ui_demo.c.o
.PHONY : src/ui_demo.o

# target to build an object file
src/ui_demo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_ui.dir/build.make CMakeFiles/app_ui.dir/src/ui_demo.c.o
.PHONY : src/ui_demo.c.o

src/ui_demo.i: src/ui_demo.c.i
.PHONY : src/ui_demo.i

# target to preprocess a source file
src/ui_demo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_ui.dir/build.make CMakeFiles/app_ui.dir/src/ui_demo.c.i
.PHONY : src/ui_demo.c.i

src/ui_demo.s: src/ui_demo.c.s
.PHONY : src/ui_demo.s

# target to generate assembly for a file
src/ui_demo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_ui.dir/build.make CMakeFiles/app_ui.dir/src/ui_demo.c.s
.PHONY : src/ui_demo.c.s

src/ui_font_runtime.o: src/ui_font_runtime.c.o
.PHONY : src/ui_font_runtime.o

# target to build an object file
src/ui_font_runtime.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_ui.dir/build.make CMakeFiles/app_ui.dir/src/ui_font_runtime.c.o
.PHONY : src/ui_font_runtime.c.o

src/ui_font_runtime.i: src/ui_font_runtime.c.i
.PHONY : src/ui_font_runtime.i

# target to preprocess a source file
src/ui_font_runtime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_ui.dir/build.make CMakeFiles/app_ui.dir/src/ui_font_runtime.c.i
.PHONY : src/ui_font_runtime.c.i

src/ui_font_runtime.s: src/ui_font_runtime.c.s
.PHONY : src/ui_font_runtime.s

# target to generate assembly for a file
src/ui_font_runtime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app_ui.dir/build.make CMakeFiles/app_ui.dir/src/ui_font_runtime.c.s
.PHONY : src/ui_font_runtime.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... app_ui"
	@echo "... lv_drivers"
	@echo "... lvgl"
	@echo "... lvgl-sim"
	@echo "... lvgl_demos"
	@echo "... lvgl_examples"
	@echo "... _deps/lv_drivers-src/display/fbdev.o"
	@echo "... _deps/lv_drivers-src/display/fbdev.i"
	@echo "... _deps/lv_drivers-src/display/fbdev.s"
	@echo "... _deps/lv_drivers-src/indev/evdev.o"
	@echo "... _deps/lv_drivers-src/indev/evdev.i"
	@echo "... _deps/lv_drivers-src/indev/evdev.s"
	@echo "... _deps/lv_drivers-src/sdl/sdl.o"
	@echo "... _deps/lv_drivers-src/sdl/sdl.i"
	@echo "... _deps/lv_drivers-src/sdl/sdl.s"
	@echo "... _deps/lv_drivers-src/sdl/sdl_common.o"
	@echo "... _deps/lv_drivers-src/sdl/sdl_common.i"
	@echo "... _deps/lv_drivers-src/sdl/sdl_common.s"
	@echo "... src/fonts/lv_font_cn_14.o"
	@echo "... src/fonts/lv_font_cn_14.i"
	@echo "... src/fonts/lv_font_cn_14.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ui_demo.o"
	@echo "... src/ui_demo.i"
	@echo "... src/ui_demo.s"
	@echo "... src/ui_font_runtime.o"
	@echo "... src/ui_font_runtime.i"
	@echo "... src/ui_font_runtime.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

